import { LabelFormat, MediaProfile } from './types';

export const CANONICAL_LABEL_FORMATS: LabelFormat[] = [
  // --- Small ---
  {
    id: 'fmt-small-25x38',
    name: 'Small 25×38',
    description: 'Bijouterie, petits articles, mini flacons',
    category: 'Small',
    width: 25,
    height: 38,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 1,
    bottomMargin: 1,
    leftMargin: 1,
    rightMargin: 1,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 1.5,
    printableWidth: 23,
    printableHeight: 36,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-small-30x40',
    name: 'Small 30×40',
    description: 'Petits produits, cosmétiques, accessoires',
    category: 'Small',
    width: 30,
    height: 40,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 1.5,
    bottomMargin: 1.5,
    leftMargin: 1.5,
    rightMargin: 1.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 1.5,
    printableWidth: 27,
    printableHeight: 37,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-small-32x25',
    name: 'Small 32×25',
    description: 'Étiquettes prix courtes, étiquettes volantes',
    category: 'Small',
    width: 32,
    height: 25,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 1,
    bottomMargin: 1,
    leftMargin: 1,
    rightMargin: 1,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 1.5,
    printableWidth: 30,
    printableHeight: 23,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-small-38x25',
    name: 'Small 38×25',
    description: 'Prix simples compacts, marquage de stock',
    category: 'Small',
    width: 38,
    height: 25,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 1,
    bottomMargin: 1,
    leftMargin: 1,
    rightMargin: 1,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 1.5,
    printableWidth: 36,
    printableHeight: 23,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // --- Standard Retail ---
  {
    id: 'fmt-retail-40x30',
    name: 'Retail 40×30',
    description: 'Commerce généraliste, textile, quincaillerie',
    category: 'Standard Retail',
    width: 40,
    height: 30,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 1.5,
    bottomMargin: 1.5,
    leftMargin: 1.5,
    rightMargin: 1.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 37,
    printableHeight: 27,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-retail-40x50',
    name: 'Retail 40×50',
    description: 'Prix avec référence produit et descriptif',
    category: 'Standard Retail',
    width: 40,
    height: 50,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 1.5,
    bottomMargin: 1.5,
    leftMargin: 1.5,
    rightMargin: 1.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 37,
    printableHeight: 47,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-retail-50x30',
    name: 'Retail 50×30',
    description: 'Étiquettes de gondole fines et réglettes étagées',
    category: 'Standard Retail',
    width: 50,
    height: 30,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 1.5,
    bottomMargin: 1.5,
    leftMargin: 1.5,
    rightMargin: 1.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 47,
    printableHeight: 27,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-retail-50x40',
    name: 'Retail 50×40',
    description: 'Prix standard avec code-barres EAN-13 lisible',
    category: 'Standard Retail',
    width: 50,
    height: 40,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 1.5,
    bottomMargin: 1.5,
    leftMargin: 1.5,
    rightMargin: 1.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 47,
    printableHeight: 37,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-retail-50x50',
    name: 'Retail 50×50',
    description: 'Format carré promotionnel ou badges de réduction',
    category: 'Standard Retail',
    width: 50,
    height: 50,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 46,
    printableHeight: 46,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // --- Shelf / Supermarket ---
  {
    id: 'fmt-shelf-60x40',
    name: 'Shelf 60×40',
    description: 'Gabarit de référence supermarché & distribution alimentaire',
    category: 'Shelf / Supermarket',
    width: 60,
    height: 40,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 56,
    printableHeight: 36,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-60x50',
    name: 'Shelf 60×50',
    description: 'Prix au kg/L + promotion + code-barres grand format',
    category: 'Shelf / Supermarket',
    width: 60,
    height: 50,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 56,
    printableHeight: 46,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-70x40',
    name: 'Shelf 70×40',
    description: 'Bordure de rayon allongée, lisibilité optimale',
    category: 'Shelf / Supermarket',
    width: 70,
    height: 40,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 66,
    printableHeight: 36,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-70x50',
    name: 'Shelf 70×50',
    description: 'Mise en avant tête de gondole et promotions saisonnières',
    category: 'Shelf / Supermarket',
    width: 70,
    height: 50,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 66,
    printableHeight: 46,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-80x40',
    name: 'Shelf 80×40',
    description: 'Tarification détaillée avec multi-devises et origine',
    category: 'Shelf / Supermarket',
    width: 80,
    height: 40,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 76,
    printableHeight: 36,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-80x50',
    name: 'Shelf 80×50',
    description: 'Grand format grande distribution & hypermarchés',
    category: 'Shelf / Supermarket',
    width: 80,
    height: 50,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2,
    bottomMargin: 2,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 76,
    printableHeight: 46,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-shelf-80x60',
    name: 'Shelf 80×60',
    description: 'Fiches produit complètes, composition, allergènes',
    category: 'Shelf / Supermarket',
    width: 80,
    height: 60,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2.5,
    bottomMargin: 2.5,
    leftMargin: 2.5,
    rightMargin: 2.5,
    horizontalGap: 2,
    verticalGap: 2,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 75,
    printableHeight: 55,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // --- Large / Product ---
  {
    id: 'fmt-large-100x50',
    name: 'Large 100×50',
    description: 'Articles volumineux, électroménager, signalétique',
    category: 'Large / Product',
    width: 100,
    height: 50,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 2.5,
    bottomMargin: 2.5,
    leftMargin: 2.5,
    rightMargin: 2.5,
    horizontalGap: 3,
    verticalGap: 3,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 95,
    printableHeight: 45,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-large-100x75',
    name: 'Large 100×75',
    description: 'Promotions percutantes, détails techniques complets',
    category: 'Large / Product',
    width: 100,
    height: 75,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 3,
    bottomMargin: 3,
    leftMargin: 3,
    rightMargin: 3,
    horizontalGap: 3,
    verticalGap: 3,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 94,
    printableHeight: 69,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-large-100x100',
    name: 'Large 100×100',
    description: 'Grand affichage produit, fûts, bacs de stockage',
    category: 'Large / Product',
    width: 100,
    height: 100,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 3,
    bottomMargin: 3,
    leftMargin: 3,
    rightMargin: 3,
    horizontalGap: 3,
    verticalGap: 3,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 94,
    printableHeight: 94,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-large-100x150',
    name: 'Large 100×150',
    description: 'Logistique, expédition colis, étiquette carton standard',
    category: 'Large / Product',
    width: 100,
    height: 150,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 3,
    bottomMargin: 3,
    leftMargin: 3,
    rightMargin: 3,
    horizontalGap: 3,
    verticalGap: 3,
    columns: 1,
    rows: 1,
    mediaTypeId: 'DIE_CUT',
    shape: 'Rounded Rectangle',
    cornerRadius: 2,
    printableWidth: 94,
    printableHeight: 144,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // --- Continuous ---
  {
    id: 'fmt-continuous-58mm',
    name: 'Continuous 58mm',
    description: 'Rouleau continu 58mm (imprimantes de caisse & tickets POS)',
    category: 'Continuous',
    width: 58,
    height: 80, // default display height
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 1,
    bottomMargin: 1,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 1,
    rows: 1,
    mediaTypeId: 'CONTINUOUS',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 54,
    printableHeight: 78,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'fmt-continuous-80mm',
    name: 'Continuous 80mm',
    description: 'Rouleau continu 80mm standard (ESC/POS ou thermique continu)',
    category: 'Continuous',
    width: 80,
    height: 100,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 1,
    bottomMargin: 1,
    leftMargin: 2,
    rightMargin: 2,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 1,
    rows: 1,
    mediaTypeId: 'CONTINUOUS',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 76,
    printableHeight: 98,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },

  // --- Sheet (A4 / A5 Grids) ---
  {
    id: 'fmt-sheet-a4-24',
    name: 'Planche A4 - 24 étiquettes (70×37mm)',
    description: 'Format bureautique universel 3×8 étiquettes par page A4',
    category: 'Sheet',
    width: 70,
    height: 37,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 0,
    bottomMargin: 0,
    leftMargin: 0,
    rightMargin: 0,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 3,
    rows: 8,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 70,
    printableHeight: 37,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 24,
    },
  },
  {
    id: 'fmt-sheet-a4-21',
    name: 'Planche A4 - 21 étiquettes (70×42.3mm)',
    description: 'Format A4 standard 3 colonnes × 7 lignes',
    category: 'Sheet',
    width: 70,
    height: 42.3,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 0,
    bottomMargin: 0,
    leftMargin: 0,
    rightMargin: 0,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 3,
    rows: 7,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 70,
    printableHeight: 42.3,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 21,
    },
  },
  {
    id: 'fmt-sheet-a4-14',
    name: 'Planche A4 - 14 étiquettes (105×42.4mm)',
    description: 'Format A4 2 colonnes × 7 lignes pour étiquettes larges',
    category: 'Sheet',
    width: 105,
    height: 42.4,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 0,
    bottomMargin: 0,
    leftMargin: 0,
    rightMargin: 0,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 2,
    rows: 7,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 105,
    printableHeight: 42.4,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 14,
    },
  },
  {
    id: 'fmt-sheet-a4-8',
    name: 'Planche A4 - 8 étiquettes (105×74.2mm)',
    description: 'Format A4 2 colonnes × 4 lignes (format carte postale / PLV)',
    category: 'Sheet',
    width: 105,
    height: 74.2,
    unit: 'mm',
    orientation: 'landscape',
    topMargin: 0,
    bottomMargin: 0,
    leftMargin: 0,
    rightMargin: 0,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 2,
    rows: 4,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 105,
    printableHeight: 74.2,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 8,
    },
  },
  {
    id: 'fmt-sheet-a4-4',
    name: 'Planche A4 - 4 étiquettes (105×148.5mm)',
    description: 'Format A4 2 colonnes × 2 lignes (A6 individuel)',
    category: 'Sheet',
    width: 105,
    height: 148.5,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 0,
    bottomMargin: 0,
    leftMargin: 0,
    rightMargin: 0,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 2,
    rows: 2,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 105,
    printableHeight: 148.5,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 4,
    },
  },
  {
    id: 'fmt-sheet-a4-1',
    name: 'Planche A4 - Pleine page (210×297mm)',
    description: 'Affiche A4 pleine page, signalétique rayon',
    category: 'Sheet',
    width: 210,
    height: 297,
    unit: 'mm',
    orientation: 'portrait',
    topMargin: 5,
    bottomMargin: 5,
    leftMargin: 5,
    rightMargin: 5,
    horizontalGap: 0,
    verticalGap: 0,
    columns: 1,
    rows: 1,
    mediaTypeId: 'SHEET',
    shape: 'Rectangle',
    cornerRadius: 0,
    printableWidth: 200,
    printableHeight: 287,
    isBuiltIn: true,
    isCustom: false,
    version: 1,
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    sheetConfig: {
      pageSize: 'A4',
      labelsPerPage: 1,
    },
  },
];

export const INITIAL_MEDIA_PROFILES: MediaProfile[] = [
  {
    id: 'media-roll-60mm-diecut',
    name: 'Rouleau thermique 60mm Découpé (Mandrin 25mm)',
    rollWidth: 60,
    coreDiameter: 25.4,
    mediaType: 'DIE_CUT',
    adhesiveType: 'permanent',
    compatibleLabelFormatIds: ['fmt-shelf-60x40', 'fmt-shelf-60x50'],
  },
  {
    id: 'media-roll-80mm-diecut',
    name: 'Rouleau thermique 80mm Découpé (Mandrin 25mm)',
    rollWidth: 80,
    coreDiameter: 25.4,
    mediaType: 'DIE_CUT',
    adhesiveType: 'permanent',
    compatibleLabelFormatIds: [
      'fmt-shelf-80x40',
      'fmt-shelf-80x50',
      'fmt-shelf-80x60',
      'fmt-shelf-70x40',
      'fmt-shelf-70x50',
    ],
  },
  {
    id: 'media-roll-102mm-diecut',
    name: 'Rouleau thermique 102mm / 4 pouces (Mandrin 76mm)',
    rollWidth: 102,
    coreDiameter: 76.2,
    mediaType: 'DIE_CUT',
    adhesiveType: 'permanent',
    compatibleLabelFormatIds: [
      'fmt-large-100x50',
      'fmt-large-100x75',
      'fmt-large-100x100',
      'fmt-large-100x150',
    ],
  },
  {
    id: 'media-roll-80mm-continuous',
    name: 'Rouleau continu thermique 80mm',
    rollWidth: 80,
    coreDiameter: 12.7,
    mediaType: 'CONTINUOUS',
    adhesiveType: 'removable',
    compatibleLabelFormatIds: ['fmt-continuous-80mm'],
  },
  {
    id: 'media-sheet-a4',
    name: 'Planches A4 universelles autocollantes',
    rollWidth: 210,
    coreDiameter: 0,
    mediaType: 'SHEET',
    adhesiveType: 'permanent',
    compatibleLabelFormatIds: [
      'fmt-sheet-a4-24',
      'fmt-sheet-a4-21',
      'fmt-sheet-a4-14',
      'fmt-sheet-a4-8',
      'fmt-sheet-a4-4',
      'fmt-sheet-a4-1',
    ],
  },
];
