import { PrinterModel } from './types';

export const CANONICAL_PRINTER_MODELS: PrinterModel[] = [
  // --- Zebra ---
  {
    id: 'model-zebra-zd421',
    manufacturer: 'Zebra',
    model: 'ZD421',
    family: 'Desktop ZD-Series',
    printerType: 'Label Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 15,
    maxMediaHeight: 991,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'NOTCH'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417'],
      maxPrintSpeedIps: 6,
    },
  },
  {
    id: 'model-zebra-zd621',
    manufacturer: 'Zebra',
    model: 'ZD621',
    family: 'Desktop ZD-Series Performance',
    printerType: 'Label Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 15,
    maxMediaHeight: 991,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'NOTCH', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: true,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417', 'Aztec'],
      maxPrintSpeedIps: 8,
    },
  },
  {
    id: 'model-zebra-zt411',
    manufacturer: 'Zebra',
    model: 'ZT411',
    family: 'Industrial ZT-Series',
    printerType: 'Industrial Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300, 600],
    maxMediaWidth: 114,
    minMediaWidth: 25,
    maxMediaHeight: 3810,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Bluetooth', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'NOTCH', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417', 'Aztec'],
      maxPrintSpeedIps: 14,
    },
  },

  // --- TSC / Printronix ---
  {
    id: 'model-tsc-tx200',
    manufacturer: 'TSC',
    model: 'TX200',
    family: 'TX Series Desktop',
    printerType: 'Label Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 19,
    maxMediaHeight: 25400,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'TSPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'PDF417'],
      maxPrintSpeedIps: 8,
    },
  },
  {
    id: 'model-tsc-mb240',
    manufacturer: 'TSC',
    model: 'MB240',
    family: 'MB Series Light Industrial',
    printerType: 'Industrial Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300],
    maxMediaWidth: 118,
    minMediaWidth: 20,
    maxMediaHeight: 25400,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Serial'],
    commandLanguage: 'TSPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417'],
      maxPrintSpeedIps: 10,
    },
  },

  // --- SATO ---
  {
    id: 'model-sato-cl4nx',
    manufacturer: 'SATO',
    model: 'CL4NX Plus',
    family: 'CL4NX Industrial',
    printerType: 'Industrial Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 305, 609],
    maxMediaWidth: 128,
    minMediaWidth: 22,
    maxMediaHeight: 2500,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'SATO',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD', 'NOTCH'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: true,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417'],
      maxPrintSpeedIps: 14,
    },
  },
  {
    id: 'model-sato-cg408',
    manufacturer: 'SATO',
    model: 'CG408',
    family: 'Compact Desktop',
    printerType: 'Label Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [203, 305],
    maxMediaWidth: 104,
    minMediaWidth: 12,
    maxMediaHeight: 300,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Serial'],
    commandLanguage: 'SATO',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK'],
    capabilities: {
      cutter: true,
      peeler: false,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 4,
    },
  },

  // --- Honeywell ---
  {
    id: 'model-honeywell-pm45',
    manufacturer: 'Honeywell',
    model: 'PM45',
    family: 'PM Series Industrial',
    printerType: 'Industrial Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300, 406, 600],
    maxMediaWidth: 114,
    minMediaWidth: 19,
    maxMediaHeight: 4800,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix'],
      maxPrintSpeedIps: 14,
    },
  },
  {
    id: 'model-honeywell-pc43',
    manufacturer: 'Honeywell',
    model: 'PC43d',
    family: 'PC Series Desktop',
    printerType: 'Label Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [203, 300],
    maxMediaWidth: 104,
    minMediaWidth: 19,
    maxMediaHeight: 900,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'NOTCH'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 8,
    },
  },

  // --- Brother ---
  {
    id: 'model-brother-td4550',
    manufacturer: 'Brother',
    model: 'TD-4550DNWB',
    family: 'TD Professional Series',
    printerType: 'Label Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [300],
    maxMediaWidth: 108,
    minMediaWidth: 19,
    maxMediaHeight: 3000,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix'],
      maxPrintSpeedIps: 6,
    },
  },

  // --- BIXOLON ---
  {
    id: 'model-bixolon-slp-tx400',
    manufacturer: 'BIXOLON',
    model: 'SLP-TX400',
    family: 'TX Desktop',
    printerType: 'Label Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 20,
    maxMediaHeight: 1000,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 7,
    },
  },

  // --- GoDEX ---
  {
    id: 'model-godex-rt700',
    manufacturer: 'GoDEX',
    model: 'RT700',
    family: 'RT Series Desktop',
    printerType: 'Label Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 20,
    maxMediaHeight: 1727,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Serial'],
    commandLanguage: 'TSPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK', 'FANFOLD'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 7,
    },
  },

  // --- Citizen ---
  {
    id: 'model-citizen-cls621',
    manufacturer: 'Citizen',
    model: 'CL-S621',
    family: 'CL-S Series',
    printerType: 'Label Printer',
    technology: 'Thermal Transfer',
    resolutionOptions: [203],
    maxMediaWidth: 118,
    minMediaWidth: 12.5,
    maxMediaHeight: 1625,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Serial'],
    commandLanguage: 'ZPL',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK'],
    capabilities: {
      cutter: true,
      peeler: true,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 4,
    },
  },

  // --- Epson POS ---
  {
    id: 'model-epson-tmt88vi',
    manufacturer: 'Epson',
    model: 'TM-T88VI',
    family: 'POS Receipt Terminal',
    printerType: 'POS-Receipt Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [180, 203],
    maxMediaWidth: 80,
    minMediaWidth: 58,
    maxMediaHeight: 1000,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Serial'],
    commandLanguage: 'ESC/POS',
    supportedMediaTypes: ['CONTINUOUS'],
    capabilities: {
      cutter: true,
      peeler: false,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 13.8,
    },
  },

  // --- Generic Thermal Printer ---
  {
    id: 'model-generic-thermal',
    manufacturer: 'Generic',
    model: 'Thermique Universelle (ZPL/TSPL/ESC)',
    family: 'Generic Thermal',
    printerType: 'Label Printer',
    technology: 'Direct Thermal',
    resolutionOptions: [203, 300],
    maxMediaWidth: 108,
    minMediaWidth: 20,
    maxMediaHeight: 1500,
    supportedConnectionTypes: ['USB', 'Ethernet', 'Wi-Fi', 'Bluetooth', 'Windows Driver', 'Network Share'],
    commandLanguage: 'Generic',
    supportedMediaTypes: ['DIE_CUT', 'CONTINUOUS', 'BLACK_MARK'],
    capabilities: {
      cutter: false,
      peeler: false,
      tearOff: true,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'Code 128', 'Code 39', 'QR Code'],
      maxPrintSpeedIps: 5,
    },
  },

  // --- System / Office Printer (Laser/Inkjet OS Driver) ---
  {
    id: 'model-system-office',
    manufacturer: 'Pilote Système / Bureautique',
    model: 'Imprimante Standard (Pilote OS)',
    family: 'Office Driver',
    printerType: 'Office Printer',
    technology: 'Laser/Inkjet',
    resolutionOptions: [300, 600, 1200],
    maxMediaWidth: 215.9, // A4 / Letter width
    minMediaWidth: 105,
    maxMediaHeight: 355.6,
    supportedConnectionTypes: ['Windows Driver', 'Network Share', 'USB', 'Wi-Fi'],
    commandLanguage: 'SystemDriver',
    supportedMediaTypes: ['SHEET'],
    capabilities: {
      cutter: false,
      peeler: false,
      tearOff: false,
      linerless: false,
      supportedSymbologies: ['EAN-13', 'EAN-8', 'UPC-A', 'Code 128', 'Code 39', 'QR Code', 'Data Matrix', 'PDF417'],
    },
    isLiveQueried: true,
  },
];
