export interface PWACredentials {
  instanceId: string;
  instanceName: string;
  sessionToken: string; // Cryptographic SHA-256 session token
  authPin: string; // 4-digit or 6-digit access PIN
  secretSalt: string;
  issuedAt: string;
  expiresAt: string;
}

// -------------------------------------------------------------
// V2.0 OFFICIAL INTEROP PROTOCOL CONTRACTS (Desktop ⇄ Mobile)
// -------------------------------------------------------------

/**
 * QR Code JSON format generated by Desktop E-Studio
 */
export interface EstudioPairV2Payload {
  protocol: 'estudio-pair-v2';
  host: string;
  port: number;
  stationId: string;
  stationName: string;
  token: string;
  pin: string;
  signature: string; // sha256(stationId + token + pin)
}

/**
 * Item in table scanned on Android Mobile
 */
export interface MobileTableItem {
  id: string;
  barcode: string;
  designation: string;
  templateId?: string;
  quantity: number; // Desired label count
  facing?: number;
  regularPrice?: number;
  discountPrice?: number | null;
  scannedAt: number;
}

/**
 * Full table payload sent via POST /api/v2/tables/import
 */
export interface MobileTablePayload {
  tableId: string; // e.g. "TB-849201"
  tableName: string; // e.g. "Changement Prix Épicerie"
  colorTag?: 'GREEN' | 'BLUE' | 'RED' | 'YELLOW' | 'PURPLE';
  department?: string; // e.g. "Épicerie"
  operatorName: string; // e.g. "Jean Dupont"
  isLocked: boolean;
  createdAt: number;
  exportedAt: number;
  itemsCount: number;
  totalLabelsCount: number;
  items: MobileTableItem[];
}

export interface HandshakeRequest {
  deviceId: string;
  deviceName: string;
  operatorName: string;
  token: string;
  pin?: string;
  clientTimestamp: number;
}

export interface HandshakeResponse {
  status: 'PAIRED' | 'REJECTED';
  stationId: string;
  stationName?: string;
  storeName: string;
  sessionToken: string;
  catalogVersion: string;
  availableTemplates: Array<{
    id: string;
    name: string;
    type: string;
  }>;
  serverTimestamp?: number;
}

export interface CatalogSyncItem {
  sku: string;
  barcode: string;
  designation: string;
  department: string;
  category?: string;
  regularPrice: number;
  promoPrice?: number | null;
  unit?: string;
  stock?: number;
}

export interface MobileScanItem {
  id: string;
  code: string; // Barcode, EAN13, Code128, QR Code, or Part Number
  designation?: string;
  price?: number;
  promoPrice?: number;
  unitPrice?: string;
  quantity: number; // Desired number of printed labels
  facing?: number;
  targetTemplateId?: string; // Optional gabarit override
  note?: string;
  scannedAt: string;
}

export interface MobileScanLot {
  id: string;
  name: string; // e.g., "Rayon Épicerie - Réassort Lundi"
  createdAt: string;
  updatedAt: string;
  operatorName: string;
  deviceName: string;
  deviceType: 'ios' | 'android' | 'pwa' | 'native_terminal';
  status: 'draft' | 'ready' | 'received' | 'spooled' | 'archived';
  targetTemplateId?: string; // Default template for this lot
  items: MobileScanItem[];
  sharedWithInstances?: string[];
  syncMethod?: 'direct_lan' | 'cellular_tunnel' | 'manual_sync' | 'p2p_relay';
  totalLabelsCount?: number;
  department?: string;
  colorTag?: 'GREEN' | 'BLUE' | 'RED' | 'YELLOW' | 'PURPLE';
  tableId?: string;
  credentialsUsed?: {
    instanceId: string;
    tokenHash: string;
  };
}

export type NetworkConnectionMode = 'internet_public' | 'wifi_lan' | 'custom_tunnel';

export interface SyncConnectionConfig {
  instanceId: string;
  instanceName: string;
  storeName?: string;
  hostAddress: string;
  port: number;
  publicHostUrl: string; // Public / Internet URL accessible via 4G/5G/WAN
  connectionMode: NetworkConnectionMode;
  credentials: PWACredentials;
  allowLanDiscovery: boolean;
  allowCellularTunnel: boolean;
  saveDataOnMetered: boolean;
  mdnsServiceName?: string;
  udpDiscoveryPort?: number;
}

export interface MobileSyncMessage {
  type: 'LOT_PUSH' | 'TABLE_IMPORT' | 'TEMPLATE_CATALOG_SYNC' | 'HEARTBEAT' | 'LOT_ACK' | 'INSTANCE_ANNOUNCE';
  payload: any;
  senderInstanceId: string;
  timestamp: string;
  authTokenHash?: string;
}
