import { LabelTemplate } from '../types';

export interface StandardFormatPreset {
  id: string;
  name: string;
  brand: 'Avery' | 'Standard Retail' | 'Logistique' | 'Bouteille & Rond';
  width_mm: number;
  height_mm: number;
  pageSize: 'A4' | 'A3' | 'A5' | 'ROLL';
  labelsPerPage: number;
  description: string;
  recommendedUse: string;
  template: Partial<LabelTemplate>;
}

export const AVERY_STANDARD_CATALOG: StandardFormatPreset[] = [
  {
    id: 'avery-l7160',
    name: 'Avery L7160 (63.5 × 38.1 mm)',
    brand: 'Avery',
    width_mm: 63.5,
    height_mm: 38.1,
    pageSize: 'A4',
    labelsPerPage: 21,
    description: 'Format standard universel 3 colonnes × 7 lignes sur planche A4',
    recommendedUse: 'Balisage gondole, étiquetage produits épicerie et adresses',
    template: {
      name: 'Avery L7160 (63.5x38.1mm)',
      width_mm: 63.5,
      height_mm: 38.1,
      inner_margins_mm: { top: 2, bottom: 2, left: 2, right: 2 },
      outer_margins_mm: { top: 0, bottom: 0, left: 0, right: 0 },
      bg_color: '#FFFFFF',
      bg_opacity: 1.0,
      items: [
        {
          id: 'item-store',
          type: 'text',
          x_mm: 2,
          y_mm: 2,
          w_mm: 59.5,
          h_mm: 4,
          rotation: 0,
          z_index: 1,
          locked: false,
          binding_key: 'STORE_NAME',
          text: 'SUPERMARCHÉ CENTRAL',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 7,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#64748b',
          alignment: 'left',
          valign: 'middle',
          wrap: false,
          overflow: 'clip',
        },
        {
          id: 'item-title',
          type: 'text',
          x_mm: 2,
          y_mm: 6.5,
          w_mm: 59.5,
          h_mm: 9,
          rotation: 0,
          z_index: 2,
          locked: false,
          binding_key: 'ITEMNAME',
          text: 'Article Grand Format 250g',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 10,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0f172a',
          alignment: 'left',
          valign: 'top',
          wrap: true,
          overflow: 'autofit_shrink',
        },
        {
          id: 'item-price',
          type: 'text',
          x_mm: 26,
          y_mm: 17,
          w_mm: 35.5,
          h_mm: 12,
          rotation: 0,
          z_index: 3,
          locked: false,
          binding_key: 'SELLING_PRICE',
          text: '2 450',
          font_family: 'Oswald',
          font_size_pt: 20,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0284c7',
          alignment: 'right',
          valign: 'middle',
          wrap: false,
          overflow: 'autofit_shrink',
          is_price: true,
          currency_symbol: 'FCFA',
          currency_position: 'after',
        },
        {
          id: 'item-barcode',
          type: 'barcode',
          x_mm: 2,
          y_mm: 22,
          w_mm: 26,
          h_mm: 13,
          rotation: 0,
          z_index: 4,
          locked: false,
          binding_key: 'PRODUCT_SCAN',
          code: '3250390123456',
          barcode_type: 'ean13',
          show_text: true,
          bar_color: '#000000',
        },
      ],
    },
  },
  {
    id: 'avery-3474',
    name: 'Avery 3474 (70.0 × 37.0 mm)',
    brand: 'Avery',
    width_mm: 70.0,
    height_mm: 37.0,
    pageSize: 'A4',
    labelsPerPage: 24,
    description: 'Format haute densité 3 colonnes × 8 lignes sur planche A4',
    recommendedUse: 'Étiquetage prix et code-barres grande distribution',
    template: {
      name: 'Avery 3474 (70x37mm)',
      width_mm: 70.0,
      height_mm: 37.0,
      inner_margins_mm: { top: 2, bottom: 2, left: 2, right: 2 },
      outer_margins_mm: { top: 0, bottom: 0, left: 0, right: 0 },
      bg_color: '#FFFFFF',
      bg_opacity: 1.0,
      items: [
        {
          id: 'item-title-3474',
          type: 'text',
          x_mm: 2,
          y_mm: 2,
          w_mm: 66,
          h_mm: 9,
          rotation: 0,
          z_index: 1,
          locked: false,
          binding_key: 'ITEMNAME',
          text: 'Désignation Article 70x37',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 10,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0f172a',
          alignment: 'left',
          valign: 'top',
          wrap: true,
          overflow: 'autofit_shrink',
        },
        {
          id: 'item-price-3474',
          type: 'text',
          x_mm: 30,
          y_mm: 12,
          w_mm: 38,
          h_mm: 14,
          rotation: 0,
          z_index: 2,
          locked: false,
          binding_key: 'SELLING_PRICE',
          text: '1 950',
          font_family: 'Oswald',
          font_size_pt: 22,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#e11d48',
          alignment: 'right',
          valign: 'middle',
          wrap: false,
          overflow: 'autofit_shrink',
          is_price: true,
          currency_symbol: 'FCFA',
          currency_position: 'after',
        },
        {
          id: 'item-barcode-3474',
          type: 'barcode',
          x_mm: 2,
          y_mm: 16,
          w_mm: 26,
          h_mm: 18,
          rotation: 0,
          z_index: 3,
          locked: false,
          binding_key: 'PRODUCT_SCAN',
          code: '3700012345678',
          barcode_type: 'ean13',
          show_text: true,
          bar_color: '#000000',
        },
      ],
    },
  },
  {
    id: 'gondole-standard',
    name: 'Étiquette Gondole Rayon (65.0 × 35.0 mm)',
    brand: 'Standard Retail',
    width_mm: 65.0,
    height_mm: 35.0,
    pageSize: 'A4',
    labelsPerPage: 21,
    description: 'Format standard des réglettes de gondoles supermarchés',
    recommendedUse: 'Porte-étiquettes rail PVC de linéaire de supermarché',
    template: {
      name: 'Gondole Standard 65x35mm',
      width_mm: 65.0,
      height_mm: 35.0,
      inner_margins_mm: { top: 1.5, bottom: 1.5, left: 1.5, right: 1.5 },
      outer_margins_mm: { top: 0, bottom: 0, left: 0, right: 0 },
      bg_color: '#FFFFFF',
      bg_opacity: 1.0,
      items: [
        {
          id: 'g-title',
          type: 'text',
          x_mm: 2,
          y_mm: 2,
          w_mm: 61,
          h_mm: 8,
          rotation: 0,
          z_index: 1,
          locked: false,
          binding_key: 'ITEMNAME',
          text: 'Article Gondole 65x35',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 9,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0f172a',
          alignment: 'left',
          valign: 'top',
          wrap: true,
          overflow: 'autofit_shrink',
        },
        {
          id: 'g-price',
          type: 'text',
          x_mm: 28,
          y_mm: 11,
          w_mm: 35,
          h_mm: 12,
          rotation: 0,
          z_index: 2,
          locked: false,
          binding_key: 'SELLING_PRICE',
          text: '3 200',
          font_family: 'Oswald',
          font_size_pt: 20,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0284c7',
          alignment: 'right',
          valign: 'middle',
          wrap: false,
          overflow: 'autofit_shrink',
          is_price: true,
          currency_symbol: 'FCFA',
          currency_position: 'after',
        },
        {
          id: 'g-unit-price',
          type: 'text',
          x_mm: 28,
          y_mm: 23,
          w_mm: 35,
          h_mm: 4,
          rotation: 0,
          z_index: 3,
          locked: false,
          text: '12,80 € / kg',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 6,
          font_weight: '500',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#64748b',
          alignment: 'right',
          valign: 'middle',
          wrap: false,
          overflow: 'clip',
          calculation_mode: 'unit_price',
          unit_price_config: {
            enabled: true,
            weight_volume_key: 'NET_WEIGHT_KG',
            measure_unit: 'kg',
          },
        },
        {
          id: 'g-barcode',
          type: 'barcode',
          x_mm: 2,
          y_mm: 12,
          w_mm: 24,
          h_mm: 16,
          rotation: 0,
          z_index: 4,
          locked: false,
          binding_key: 'PRODUCT_SCAN',
          code: '3250390123456',
          barcode_type: 'ean13',
          show_text: true,
          bar_color: '#000000',
        },
      ],
    },
  },
  {
    id: 'logistique-100x150',
    name: 'Étiquette Colis Logistique (100.0 × 150.0 mm)',
    brand: 'Logistique',
    width_mm: 100.0,
    height_mm: 150.0,
    pageSize: 'ROLL',
    labelsPerPage: 1,
    description: 'Format standard expédition palette et carton pour imprimante thermique',
    recommendedUse: 'Zebra ZPL, transporteurs (Colissimo, DHL, Chronopost, Schenker)',
    template: {
      name: 'Colis Logistique 100x150mm',
      width_mm: 100.0,
      height_mm: 150.0,
      inner_margins_mm: { top: 4, bottom: 4, left: 4, right: 4 },
      outer_margins_mm: { top: 0, bottom: 0, left: 0, right: 0 },
      bg_color: '#FFFFFF',
      bg_opacity: 1.0,
      items: [
        {
          id: 'log-header-box',
          type: 'shape',
          x_mm: 4,
          y_mm: 4,
          w_mm: 92,
          h_mm: 16,
          rotation: 0,
          z_index: 1,
          locked: false,
          fill_color: '#0f172a',
          border_color: '#0f172a',
          border_width: 1,
          corner_radius: 2,
        },
        {
          id: 'log-header-text',
          type: 'text',
          x_mm: 6,
          y_mm: 6,
          w_mm: 88,
          h_mm: 12,
          rotation: 0,
          z_index: 2,
          locked: false,
          text: 'EXPÉDITION LOGISTIQUE - STANDARD',
          font_family: 'Oswald',
          font_size_pt: 13,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#ffffff',
          alignment: 'center',
          valign: 'middle',
          wrap: false,
          overflow: 'clip',
        },
        {
          id: 'log-dest-title',
          type: 'text',
          x_mm: 4,
          y_mm: 24,
          w_mm: 92,
          h_mm: 5,
          rotation: 0,
          z_index: 3,
          locked: false,
          text: 'DESTINATAIRE :',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 8,
          font_weight: 'bold',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#64748b',
          alignment: 'left',
          valign: 'middle',
          wrap: false,
          overflow: 'clip',
        },
        {
          id: 'log-dest-name',
          type: 'text',
          x_mm: 4,
          y_mm: 30,
          w_mm: 92,
          h_mm: 8,
          rotation: 0,
          z_index: 4,
          locked: false,
          binding_key: 'STORE_NAME',
          text: 'CENTRE DE DISTRIBUTION NORD',
          font_family: 'Plus Jakarta Sans',
          font_size_pt: 12,
          font_weight: '800',
          font_style: 'normal',
          text_decoration: 'none',
          text_color: '#0f172a',
          alignment: 'left',
          valign: 'middle',
          wrap: false,
          overflow: 'clip',
        },
        {
          id: 'log-barcode-main',
          type: 'barcode',
          x_mm: 10,
          y_mm: 80,
          w_mm: 80,
          h_mm: 45,
          rotation: 0,
          z_index: 5,
          locked: false,
          binding_key: 'PRODUCT_SCAN',
          code: '3250390123456',
          barcode_type: 'code128',
          show_text: true,
          bar_color: '#000000',
        },
      ],
    },
  },
];
