import { LabelTemplate } from './types';

export const DEFAULT_TEMPLATES: LabelTemplate[] = [
  {
    schema_version: 1,
    name: "Étiquette Rayon Supermarché (100 x 50 mm)",
    width_mm: 100.0,
    height_mm: 50.0,
    inner_margins_mm: { top: 2.0, bottom: 2.0, left: 2.0, right: 2.0 },
    outer_margins_mm: { top: 1.0, bottom: 1.0, left: 1.0, right: 1.0 },
    bg_color: "#FFFFFF",
    bg_opacity: 1.0,
    background_image_path: null,
    background_image_opacity: 0.35,
    background_image_fit: "contain",
    background_image_visible: true,
    background_image_locked: true,
    background_image_in_output: false,
    items: [
      // Store name
      {
        id: "item_store",
        type: "text",
        x_mm: 4.0,
        y_mm: 3.0,
        w_mm: 45.0,
        h_mm: 6.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        binding_key: "STORE_NAME",
        text: "SUPERMARCHÉ EXPRESS",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 8.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#1e293b",
        alignment: "left",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Category / Department
      {
        id: "item_dept",
        type: "text",
        x_mm: 52.0,
        y_mm: 3.0,
        w_mm: 44.0,
        h_mm: 6.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        binding_key: "CATEGORY_NAME",
        text: "ÉPICERIE SUCRÉE",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 7.5,
        font_weight: "600",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "right",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Divider Line
      {
        id: "item_div1",
        type: "line",
        x_mm: 4.0,
        y_mm: 9.5,
        w_mm: 92.0,
        h_mm: 1.0,
        rotation: 0,
        z_index: 1,
        locked: true,
        color: "#cbd5e1",
        thickness: 1.0,
        style: "solid",
      },
      // Article Name (Main)
      {
        id: "item_name",
        type: "text",
        x_mm: 4.0,
        y_mm: 11.5,
        w_mm: 58.0,
        h_mm: 16.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "ITEMNAME",
        text: "Café Moulu Pur Arabica 250g",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 13.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#0f172a",
        alignment: "left",
        valign: "top",
        wrap: true,
        overflow: "autofit_shrink",
      },
      // Selling Price Highlight Box
      {
        id: "item_price_box",
        type: "shape",
        x_mm: 63.0,
        y_mm: 11.5,
        w_mm: 33.0,
        h_mm: 20.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        fill_color: "#f8fafc",
        border_color: "#0284c7",
        border_width: 1.5,
        corner_radius: 3.0,
      },
      // Selling Price Text
      {
        id: "item_price_val",
        type: "text",
        x_mm: 64.0,
        y_mm: 12.5,
        w_mm: 31.0,
        h_mm: 14.0,
        rotation: 0,
        z_index: 3,
        locked: false,
        binding_key: "SELLING_PRICE",
        text: "2 450",
        font_family: "Oswald",
        font_size_pt: 22.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#0369a1",
        alignment: "center",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Price Currency Label
      {
        id: "item_price_cur",
        type: "text",
        x_mm: 64.0,
        y_mm: 26.5,
        w_mm: 31.0,
        h_mm: 4.5,
        rotation: 0,
        z_index: 3,
        locked: false,
        text: "FCFA / Unité",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 7.5,
        font_weight: "600",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#0284c7",
        alignment: "center",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Barcode
      {
        id: "item_barcode",
        type: "barcode",
        x_mm: 4.0,
        y_mm: 29.0,
        w_mm: 46.0,
        h_mm: 16.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PRODUCT_SCAN",
        code: "3250390123456",
        barcode_type: "ean13",
        show_text: true,
        bar_color: "#000000",
      },
      // SKU / Part No
      {
        id: "item_sku",
        type: "text",
        x_mm: 53.0,
        y_mm: 33.0,
        w_mm: 43.0,
        h_mm: 5.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PARTNO",
        text: "RÉF: ART-9042",
        font_family: "JetBrains Mono",
        font_size_pt: 7.0,
        font_weight: "normal",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "right",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Unit packing / weight
      {
        id: "item_unit",
        type: "text",
        x_mm: 53.0,
        y_mm: 39.0,
        w_mm: 43.0,
        h_mm: 5.5,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PACK_UNIT",
        text: "9.80 €/kg • 250g",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 7.5,
        font_weight: "500",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#475569",
        alignment: "right",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
    ],
  },
  {
    schema_version: 1,
    name: "Étiquette Cash & Carry Paliers (105 x 74 mm - A7)",
    width_mm: 105.0,
    height_mm: 74.0,
    inner_margins_mm: { top: 3.0, bottom: 3.0, left: 3.0, right: 3.0 },
    outer_margins_mm: { top: 1.5, bottom: 1.5, left: 1.5, right: 1.5 },
    bg_color: "#FFFFFF",
    bg_opacity: 1.0,
    background_image_path: null,
    background_image_opacity: 0.35,
    background_image_fit: "contain",
    background_image_visible: true,
    background_image_locked: true,
    background_image_in_output: false,
    items: [
      // Header brand
      {
        id: "item_cc_brand",
        type: "text",
        x_mm: 5.0,
        y_mm: 4.0,
        w_mm: 50.0,
        h_mm: 6.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        binding_key: "BRAND_INFO",
        text: "GROS & DEMI-GROS",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 8.5,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#b91c1c",
        alignment: "left",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // SKU
      {
        id: "item_cc_sku",
        type: "text",
        x_mm: 60.0,
        y_mm: 4.0,
        w_mm: 40.0,
        h_mm: 6.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        binding_key: "PARTNO",
        text: "SKU: CC-5520",
        font_family: "JetBrains Mono",
        font_size_pt: 7.5,
        font_weight: "600",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "right",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Item Name
      {
        id: "item_cc_name",
        type: "text",
        x_mm: 5.0,
        y_mm: 11.0,
        w_mm: 95.0,
        h_mm: 12.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "ITEMNAME",
        text: "Huile de Tournesol Raffinée 1L - Carton x15",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 13.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#0f172a",
        alignment: "left",
        valign: "top",
        wrap: true,
        overflow: "autofit_shrink",
      },
      // Standard Retail Price Banner
      {
        id: "item_std_box",
        type: "shape",
        x_mm: 5.0,
        y_mm: 24.0,
        w_mm: 44.0,
        h_mm: 18.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        fill_color: "#f8fafc",
        border_color: "#cbd5e1",
        border_width: 1.0,
        corner_radius: 2.0,
      },
      {
        id: "item_std_lbl",
        type: "text",
        x_mm: 6.0,
        y_mm: 25.0,
        w_mm: 42.0,
        h_mm: 4.5,
        rotation: 0,
        z_index: 2,
        locked: false,
        text: "PRIX AU DÉTAIL (1 carton)",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 6.5,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "center",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      {
        id: "item_std_price",
        type: "text",
        x_mm: 6.0,
        y_mm: 30.0,
        w_mm: 42.0,
        h_mm: 11.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "SELLING_PRICE",
        text: "14 500 FCFA",
        font_family: "Oswald",
        font_size_pt: 16.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#1e293b",
        alignment: "center",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      // Tier 1 (Cash & Carry Tier)
      {
        id: "item_tier1",
        type: "tier_price",
        x_mm: 51.0,
        y_mm: 24.0,
        w_mm: 49.0,
        h_mm: 8.5,
        rotation: 0,
        z_index: 2,
        locked: false,
        primary_tier: 1,
        prefix_text: "Dès",
        unit_label: "FCFA",
        strict_required: false,
        fallback_to_base_price: true,
      },
      // Tier 2 (Wholesale / Palette)
      {
        id: "item_tier2",
        type: "tier_price",
        x_mm: 51.0,
        y_mm: 33.5,
        w_mm: 49.0,
        h_mm: 8.5,
        rotation: 0,
        z_index: 2,
        locked: false,
        primary_tier: 2,
        prefix_text: "Palette dès",
        unit_label: "FCFA",
        strict_required: false,
        fallback_to_base_price: true,
      },
      // Barcode
      {
        id: "item_cc_barcode",
        type: "barcode",
        x_mm: 5.0,
        y_mm: 44.0,
        w_mm: 54.0,
        h_mm: 17.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PRODUCT_SCAN",
        code: "3700012345678",
        barcode_type: "ean13",
        show_text: true,
        bar_color: "#000000",
      },
      // QR Code for Spec sheet or reorder
      {
        id: "item_cc_qr",
        type: "qrcode",
        x_mm: 78.0,
        y_mm: 44.0,
        w_mm: 22.0,
        h_mm: 22.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        content: "https://estudio.stock/reorder/CC-5520",
        module_color: "#000000",
        background_color: "#FFFFFF",
      },
      // Footer packaging note
      {
        id: "item_cc_foot",
        type: "text",
        x_mm: 5.0,
        y_mm: 63.0,
        w_mm: 70.0,
        h_mm: 6.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "CASE_UNIT",
        text: "Conditionnement: Palette 40 cartons • TVA 18% incluse",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 7.0,
        font_weight: "normal",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "left",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
    ],
  },
  {
    schema_version: 1,
    name: "Étiquette Produit Compacte (70 x 35 mm)",
    width_mm: 70.0,
    height_mm: 35.0,
    inner_margins_mm: { top: 2.0, bottom: 2.0, left: 2.0, right: 2.0 },
    outer_margins_mm: { top: 1.0, bottom: 1.0, left: 1.0, right: 1.0 },
    bg_color: "#FFFFFF",
    bg_opacity: 1.0,
    background_image_path: null,
    background_image_opacity: 0.35,
    background_image_fit: "contain",
    background_image_visible: true,
    background_image_locked: true,
    background_image_in_output: false,
    items: [
      {
        id: "item_s_name",
        type: "text",
        x_mm: 3.0,
        y_mm: 3.0,
        w_mm: 42.0,
        h_mm: 10.0,
        rotation: 0,
        z_index: 1,
        locked: false,
        binding_key: "ITEMNAME",
        text: "Biscuits Beurre Salé 150g",
        font_family: "Plus Jakarta Sans",
        font_size_pt: 9.5,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#0f172a",
        alignment: "left",
        valign: "top",
        wrap: true,
        overflow: "autofit_shrink",
      },
      {
        id: "item_s_price",
        type: "text",
        x_mm: 46.0,
        y_mm: 3.0,
        w_mm: 21.0,
        h_mm: 10.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "SELLING_PRICE",
        text: "850 F",
        font_family: "Oswald",
        font_size_pt: 16.0,
        font_weight: "bold",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#dc2626",
        alignment: "right",
        valign: "middle",
        wrap: false,
        overflow: "autofit_shrink",
      },
      {
        id: "item_s_bar",
        type: "barcode",
        x_mm: 3.0,
        y_mm: 14.0,
        w_mm: 44.0,
        h_mm: 16.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PRODUCT_SCAN",
        code: "7612345678901",
        barcode_type: "ean13",
        show_text: true,
        bar_color: "#000000",
      },
      {
        id: "item_s_ref",
        type: "text",
        x_mm: 48.0,
        y_mm: 16.0,
        w_mm: 19.0,
        h_mm: 14.0,
        rotation: 0,
        z_index: 2,
        locked: false,
        binding_key: "PARTNO",
        text: "LOT-88B\nRAYON 4",
        font_family: "JetBrains Mono",
        font_size_pt: 7.0,
        font_weight: "600",
        font_style: "normal",
        text_decoration: "none",
        text_color: "#64748b",
        alignment: "right",
        valign: "middle",
        wrap: true,
        overflow: "autofit_shrink",
      },
    ],
  },
];
