import { ProductRecord } from './types';

export const SAMPLE_PRODUCTS: ProductRecord[] = [
  {
    id: "PROD-001",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3250390123456",
    PARTNO: "CAF-250A",
    ITEMNAME: "Café Moulu Arabica Pur 250g",
    ITEMDESCRIPTION: "Torréfaction artisanale, notes chocolatées",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "BOISSONS CHAUDES",
    CATEGORY_NAME: "CAFÉ & THÉ",
    SUB_CATEGORY_NAME: "CAFÉ MOULU",
    BRAND_INFO: "Sélection Terroir",
    PACK_UNIT: "Paquet 250g",
    VENDOR_NAME: "Cafés du Monde SAS",
    SELLING_UNIT: "paquet",
    SELLING_PRICE: 2450,
    PROMOPRICE: 1950,
    DISCOUNT_PCT: 20,
    PROMO_LABEL: "-20% IMMÉDIAT",
    PROMO_PERIOD: "Du 15 au 30 Juin",
    UNIT_PRICE_TEXT: "7.80 € / kg",
    ECO_TAX: "Dont 0,05 € d'éco-part",
    ORIGIN_COUNTRY: "Colombie",
    CASE_SIZE: 12,
    CASE_UNIT: "Carton de 12 paquets",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 2200 },
      { qty: 12, unit_price: 1950 },
      { qty: 60, unit_price: 1750 },
    ],
  },
  {
    id: "PROD-002",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3700012345678",
    PARTNO: "HUI-100T",
    ITEMNAME: "Huile de Tournesol Raffinée 1L",
    ITEMDESCRIPTION: "Idéale friture et assaisonnement, riche en vitamine E",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "CORPS GRAS",
    CATEGORY_NAME: "HUILES & CONDIMENTS",
    SUB_CATEGORY_NAME: "HUILE TOURNESOL",
    BRAND_INFO: "Sol d'Or",
    PACK_UNIT: "Bouteille 1L",
    VENDOR_NAME: "Huileries Réunies",
    SELLING_UNIT: "bouteille",
    SELLING_PRICE: 1350,
    PROMOPRICE: 990,
    DISCOUNT_PCT: 25,
    PROMO_LABEL: "PRIX CHOC",
    PROMO_PERIOD: "Offre Spéciale",
    UNIT_PRICE_TEXT: "0.99 € / L",
    ORIGIN_COUNTRY: "France",
    CASE_SIZE: 15,
    CASE_UNIT: "Carton de 15 bouteilles",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 5, unit_price: 1250 },
      { qty: 15, unit_price: 1150 },
      { qty: 75, unit_price: 1050 },
    ],
  },
  {
    id: "PROD-003",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "7612345678901",
    PARTNO: "RIZ-005P",
    ITEMNAME: "Riz Parfumé Jasmin Long Grain 5kg",
    ITEMDESCRIPTION: "Riz de qualité supérieure, cuisson vapeur parfaite",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "FÉCULENTS",
    CATEGORY_NAME: "RIZ & PÂTES",
    SUB_CATEGORY_NAME: "RIZ PARFUMÉ",
    BRAND_INFO: "Royal Siam",
    PACK_UNIT: "Sac 5kg",
    VENDOR_NAME: "Import Céréales Asie",
    SELLING_UNIT: "sac",
    SELLING_PRICE: 6800,
    PROMOPRICE: 5100,
    DISCOUNT_PCT: 25,
    PROMO_LABEL: "1 SAC ACHETÉ = 1/2 PRIX",
    PROMO_PERIOD: "Ce Week-end seulement",
    UNIT_PRICE_TEXT: "1.02 € / kg",
    ORIGIN_COUNTRY: "Thaïlande",
    CASE_SIZE: 4,
    CASE_UNIT: "Balle de 4 sacs (20kg)",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 4, unit_price: 6000 },
      { qty: 10, unit_price: 5600 },
      { qty: 40, unit_price: 5200 },
    ],
  },
  {
    id: "PROD-004",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "8410234567892",
    PARTNO: "LAI-001U",
    ITEMNAME: "Lait Demi-Écrémé UHT 1L",
    ITEMDESCRIPTION: "Lait français standardisé, brique avec bouchon verseur",
    DIV_NAME: "FRAIS",
    DEPT_NAME: "PRODUITS LAITIERS",
    CATEGORY_NAME: "LAITS",
    SUB_CATEGORY_NAME: "DEMI-ÉCRÉMÉ",
    BRAND_INFO: "Pré Vert",
    PACK_UNIT: "Brique 1L",
    VENDOR_NAME: "Laiterie Centrale",
    SELLING_UNIT: "brique",
    SELLING_PRICE: 950,
    PROMOPRICE: undefined,
    UNIT_PRICE_TEXT: "0.95 € / L",
    ORIGIN_COUNTRY: "France",
    CASE_SIZE: 6,
    CASE_UNIT: "Pack de 6 briques",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 880 },
      { qty: 24, unit_price: 820 },
      { qty: 120, unit_price: 760 },
    ],
  },
  {
    id: "PROD-005",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3017620422003",
    PARTNO: "PAT-CHO1",
    ITEMNAME: "Pâte à Tartiner Noisettes & Cacao 750g",
    ITEMDESCRIPTION: "Sans huile de palme, riche en noisettes 15%",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "PETIT DÉJEUNER",
    CATEGORY_NAME: "PÂTES À TARTINER",
    SUB_CATEGORY_NAME: "CHOCOLAT",
    BRAND_INFO: "ChocoDélice",
    PACK_UNIT: "Pot verre 750g",
    VENDOR_NAME: "Confiserie Royale",
    SELLING_UNIT: "pot",
    SELLING_PRICE: 3950,
    PROMOPRICE: 2990,
    DISCOUNT_PCT: 24,
    PROMO_LABEL: "VENTE FLASH -24%",
    PROMO_PERIOD: "Jusqu'à épuisement",
    UNIT_PRICE_TEXT: "3.98 € / kg",
    ORIGIN_COUNTRY: "Italie",
    CASE_SIZE: 8,
    CASE_UNIT: "Carton de 8 pots",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 4, unit_price: 3600 },
      { qty: 8, unit_price: 3300 },
      { qty: 32, unit_price: 3000 },
    ],
  },
  {
    id: "PROD-006",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3124567890128",
    PARTNO: "EAU-015M",
    ITEMNAME: "Eau Minérale Naturelle 1.5L",
    ITEMDESCRIPTION: "Pauvre en sodium, convient pour l'alimentation des nourrissons",
    DIV_NAME: "LIQUIDES",
    DEPT_NAME: "EAUX",
    CATEGORY_NAME: "EAU PLATE",
    SUB_CATEGORY_NAME: "1.5 LITRE",
    BRAND_INFO: "Source Alpine",
    PACK_UNIT: "Bouteille 1.5L",
    VENDOR_NAME: "Eaux Minérales SA",
    SELLING_UNIT: "bouteille",
    SELLING_PRICE: 450,
    PROMOPRICE: undefined,
    UNIT_PRICE_TEXT: "0.30 € / L",
    ORIGIN_COUNTRY: "France",
    CASE_SIZE: 6,
    CASE_UNIT: "Pack de 6 bouteilles",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 400 },
      { qty: 36, unit_price: 360 },
      { qty: 180, unit_price: 320 },
    ],
  },
  // --- Assortment Cluster Sample Candidates (All Flavors/Sizes) ---
  {
    id: "PROD-007",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "8000570001017",
    PARTNO: "MART-BIA",
    ITEMNAME: "Martini Vermouth 100cl Bianco",
    ITEMDESCRIPTION: "Apéritif italien aromatisé aux herbes et vanille",
    DIV_NAME: "LIQUIDES",
    DEPT_NAME: "VINS & ALCOOLS",
    CATEGORY_NAME: "APÉRITIFS",
    BRAND_INFO: "Martini & Rossi",
    SELLING_PRICE: 1250,
    ORIGIN_COUNTRY: "Italie",
    price_tiers: [
      { min_qty: 1, unit_price: 1250, label: "Base Price", is_base: true },
      { min_qty: 3, unit_price: 1100, label: "3+ Units" },
      { min_qty: 6, unit_price: 990, label: "6+ Units" },
    ],
  },
  {
    id: "PROD-008",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "8000570001024",
    PARTNO: "MART-ROS",
    ITEMNAME: "Martini Vermouth 100cl Rosso",
    ITEMDESCRIPTION: "Apéritif italien doux aux notes de caramel et d'agrumes",
    DIV_NAME: "LIQUIDES",
    DEPT_NAME: "VINS & ALCOOLS",
    CATEGORY_NAME: "APÉRITIFS",
    BRAND_INFO: "Martini & Rossi",
    SELLING_PRICE: 1250,
    ORIGIN_COUNTRY: "Italie",
    price_tiers: [
      { min_qty: 1, unit_price: 1250, label: "Base Price", is_base: true },
      { min_qty: 3, unit_price: 1100, label: "3+ Units" },
      { min_qty: 6, unit_price: 990, label: "6+ Units" },
    ],
  },
  {
    id: "PROD-009",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "8000570001031",
    PARTNO: "MART-RSO",
    ITEMNAME: "Martini Vermouth 100cl Rosato",
    ITEMDESCRIPTION: "Apéritif italien aux notes épicées de clou de girofle et cannelle",
    DIV_NAME: "LIQUIDES",
    DEPT_NAME: "VINS & ALCOOLS",
    CATEGORY_NAME: "APÉRITIFS",
    BRAND_INFO: "Martini & Rossi",
    SELLING_PRICE: 1250,
    ORIGIN_COUNTRY: "Italie",
    price_tiers: [
      { min_qty: 1, unit_price: 1250, label: "Base Price", is_base: true },
      { min_qty: 3, unit_price: 1100, label: "3+ Units" },
      { min_qty: 6, unit_price: 990, label: "6+ Units" },
    ],
  },
  // --- Seafood Regulatory Item ---
  {
    id: "PROD-010",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "2801234015802",
    PARTNO: "POIS-SAUM",
    ITEMNAME: "Pavé de Saumon Atlantique Frais",
    ITEMDESCRIPTION: "Salmo salar élevé en eaux froides de Norvège",
    DIV_NAME: "FRAIS",
    DEPT_NAME: "MARÉE & POISSONNERIE",
    CATEGORY_NAME: "POISSONNERIE",
    SELLING_PRICE: 2490,
    PROMOPRICE: 1990,
    PROMO_LABEL: "OFFRE MARÉE",
    UNIT_PRICE_TEXT: "19.90 € / kg",
    ORIGIN_COUNTRY: "Norvège",
    FAO_ZONE: "Zone FAO 27.IIa (Mer de Norvège)",
    FISHING_GEAR: "Chalut pélagique / Aquaculture certifiée ASC",
    PRODUCTION_METHOD: "Élevé en Norvège",
  },
];

// Sample multi-row implicit data structure simulating ERP exports
export const SAMPLE_IMPLICIT_MULTI_ROW_DATA = [
  { SKU: 'EAN-32503901', ITEMNAME: 'Boisson Énergisante Monster 500ml', QTY: 1, SELLING_PRICE: 2.20, CATEGORY_NAME: 'BOISSONS' },
  { SKU: 'EAN-32503901', ITEMNAME: 'Boisson Énergisante Monster 500ml', QTY: 4, SELLING_PRICE: 1.95, CATEGORY_NAME: 'BOISSONS' },
  { SKU: 'EAN-32503901', ITEMNAME: 'Boisson Énergisante Monster 500ml', QTY: 12, SELLING_PRICE: 1.70, CATEGORY_NAME: 'BOISSONS' },
  { SKU: 'EAN-32503901', ITEMNAME: 'Boisson Énergisante Monster 500ml', QTY: 24, SELLING_PRICE: 1.50, CATEGORY_NAME: 'BOISSONS' },

  { SKU: 'EAN-32503902', ITEMNAME: 'Farine de Blé T55 Francine 1kg', QTY: 1, SELLING_PRICE: 1.40, CATEGORY_NAME: 'ÉPICERIE' },
  { SKU: 'EAN-32503902', ITEMNAME: 'Farine de Blé T55 Francine 1kg', QTY: 5, SELLING_PRICE: 1.25, CATEGORY_NAME: 'ÉPICERIE' },
  { SKU: 'EAN-32503902', ITEMNAME: 'Farine de Blé T55 Francine 1kg', QTY: 10, SELLING_PRICE: 1.10, CATEGORY_NAME: 'ÉPICERIE' },

  // Anomaly test product (missing qty, inverted price progression)
  { SKU: 'EAN-32503903', ITEMNAME: 'Piles Alcalines AA x4 PowerMax', QTY: 1, SELLING_PRICE: 4.50, CATEGORY_NAME: 'BAZAR' },
  { SKU: 'EAN-32503903', ITEMNAME: 'Piles Alcalines AA x4 PowerMax', QTY: 1, SELLING_PRICE: 4.80, CATEGORY_NAME: 'BAZAR' }, // Duplicate with conflicting price!
  { SKU: 'EAN-32503903', ITEMNAME: 'Piles Alcalines AA x4 PowerMax', QTY: 3, SELLING_PRICE: 5.20, CATEGORY_NAME: 'BAZAR' }, // Inverted price anomaly!
];

