import { ProductRecord } from './types';

export const SAMPLE_PRODUCTS: ProductRecord[] = [
  {
    id: "PROD-001",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3250390123456",
    PARTNO: "CAF-250A",
    ITEMNAME: "Café Moulu Arabica Pur 250g",
    ITEMDESCRIPTION: "Torréfaction artisanale, notes chocolatées",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "BOISSONS CHAUDES",
    CATEGORY_NAME: "CAFÉ & THÉ",
    SUB_CATEGORY_NAME: "CAFÉ MOULU",
    BRAND_INFO: "Sélection Terroir",
    PACK_UNIT: "Paquet 250g",
    VENDOR_NAME: "Cafés du Monde SAS",
    SELLING_UNIT: "paquet",
    SELLING_PRICE: 2450,
    PROMOPRICE: 2190,
    CASE_SIZE: 12,
    CASE_UNIT: "Carton de 12 paquets",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 2200 },
      { qty: 12, unit_price: 1950 },
      { qty: 60, unit_price: 1750 },
    ],
  },
  {
    id: "PROD-002",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3700012345678",
    PARTNO: "HUI-100T",
    ITEMNAME: "Huile de Tournesol Raffinée 1L",
    ITEMDESCRIPTION: "Idéale friture et assaisonnement, riche en vitamine E",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "CORPS GRAS",
    CATEGORY_NAME: "HUILES & CONDIMENTS",
    SUB_CATEGORY_NAME: "HUILE TOURNESOL",
    BRAND_INFO: "Sol d'Or",
    PACK_UNIT: "Bouteille 1L",
    VENDOR_NAME: "Huileries Réunies",
    SELLING_UNIT: "bouteille",
    SELLING_PRICE: 1350,
    PROMOPRICE: 1250,
    CASE_SIZE: 15,
    CASE_UNIT: "Carton de 15 bouteilles",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 5, unit_price: 1250 },
      { qty: 15, unit_price: 1150 },
      { qty: 75, unit_price: 1050 },
    ],
  },
  {
    id: "PROD-003",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "7612345678901",
    PARTNO: "RIZ-005P",
    ITEMNAME: "Riz Parfumé Jasmin Long Grain 5kg",
    ITEMDESCRIPTION: "Riz de qualité supérieure, cuisson vapeur parfaite",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "FÉCULENTS",
    CATEGORY_NAME: "RIZ & PÂTES",
    SUB_CATEGORY_NAME: "RIZ PARFUMÉ",
    BRAND_INFO: "Royal Siam",
    PACK_UNIT: "Sac 5kg",
    VENDOR_NAME: "Import Céréales Asie",
    SELLING_UNIT: "sac",
    SELLING_PRICE: 6800,
    PROMOPRICE: 6200,
    CASE_SIZE: 4,
    CASE_UNIT: "Balle de 4 sacs (20kg)",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 4, unit_price: 6000 },
      { qty: 10, unit_price: 5600 },
      { qty: 40, unit_price: 5200 },
    ],
  },
  {
    id: "PROD-004",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "8410234567892",
    PARTNO: "LAI-001U",
    ITEMNAME: "Lait Demi-Écrémé UHT 1L",
    ITEMDESCRIPTION: "Lait français standardisé, brique avec bouchon verseur",
    DIV_NAME: "FRAIS",
    DEPT_NAME: "PRODUITS LAITIERS",
    CATEGORY_NAME: "LAITS",
    SUB_CATEGORY_NAME: "DEMI-ÉCRÉMÉ",
    BRAND_INFO: "Pré Vert",
    PACK_UNIT: "Brique 1L",
    VENDOR_NAME: "Laiterie Centrale",
    SELLING_UNIT: "brique",
    SELLING_PRICE: 950,
    PROMOPRICE: undefined,
    CASE_SIZE: 6,
    CASE_UNIT: "Pack de 6 briques",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 880 },
      { qty: 24, unit_price: 820 },
      { qty: 120, unit_price: 760 },
    ],
  },
  {
    id: "PROD-005",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3017620422003",
    PARTNO: "PAT-CHO1",
    ITEMNAME: "Pâte à Tartiner Noisettes & Cacao 750g",
    ITEMDESCRIPTION: "Sans huile de palme, riche en noisettes 15%",
    DIV_NAME: "ÉPICERIE",
    DEPT_NAME: "PETIT DÉJEUNER",
    CATEGORY_NAME: "PÂTES À TARTINER",
    SUB_CATEGORY_NAME: "CHOCOLAT",
    BRAND_INFO: "ChocoDélice",
    PACK_UNIT: "Pot verre 750g",
    VENDOR_NAME: "Confiserie Royale",
    SELLING_UNIT: "pot",
    SELLING_PRICE: 3950,
    PROMOPRICE: 3490,
    CASE_SIZE: 8,
    CASE_UNIT: "Carton de 8 pots",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 4, unit_price: 3600 },
      { qty: 8, unit_price: 3300 },
      { qty: 32, unit_price: 3000 },
    ],
  },
  {
    id: "PROD-006",
    STORE_NAME: "SUPERMARCHÉ CENTRAL",
    PRODUCT_SCAN: "3124567890128",
    PARTNO: "EAU-015M",
    ITEMNAME: "Eau Minérale Naturelle 1.5L",
    ITEMDESCRIPTION: "Pauvre en sodium, convient pour l'alimentation des nourrissons",
    DIV_NAME: "LIQUIDES",
    DEPT_NAME: "EAUX",
    CATEGORY_NAME: "EAU PLATE",
    SUB_CATEGORY_NAME: "1.5 LITRE",
    BRAND_INFO: "Source Alpine",
    PACK_UNIT: "Bouteille 1.5L",
    VENDOR_NAME: "Eaux Minérales SA",
    SELLING_UNIT: "bouteille",
    SELLING_PRICE: 450,
    PROMOPRICE: undefined,
    CASE_SIZE: 6,
    CASE_UNIT: "Pack de 6 bouteilles",
    TAX: "TVA 18%",
    TAX_RATE: 18.0,
    TAX_TYPE: "INCLUDED",
    TIERS: [
      { qty: 6, unit_price: 400 },
      { qty: 36, unit_price: 360 },
      { qty: 180, unit_price: 320 },
    ],
  },
];
